---
title: "Home Loan Calculator"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(rsconnect)
```

```{r, echo = FALSE}
shinyApp(
  
  ui = fluidPage(
    titlePanel("Home Loan Calculator"),
    
    sidebarLayout(
      
      sidebarPanel(
        #sliderInput("homeprice", "Home Price", min=10000, max=1000000, value=20000, step=100),
        textInput("homeprice", "Home Price", value=100000),
        #sliderInput("downpayment", "Down Payment", min=0, max=100000, value=0, step=100),
        textInput("downpayment", "Down Payment", value=10000),
        sliderInput("irate", "Interest Rate", min=2.00, max=10.00, value=3.25, step=0.05),
        sliderInput("loanyear", "Loan Period", min=5, max=40, value=20, step=1)
        #sliderInput("principal", "Principal", min=100, max=10000, value=500, step=100)
      ), #sidebarPanel ends
      mainPanel(
        tabsetPanel(
          tabPanel("Summary",
                   h2("Function:"),
                   p("1. To estimate the monthly home loan repayment", style="font-family: 'times'; font-size: 12pt"),
                   p("2. To estimate how many percentage of the total payment goes into interest and principal repayment", style="font-family: 'times'; font-size: 12pt"),
                   p("3. To estimate the interest, principal repayment and balance after each monthly payment", style="font-family: 'times'; font-size: 12pt"),
                   
                   h2("How to use:"),
                   p("1. Enter your ", code("Home Price"), "(", span(em("in MYR"), style="color:blue"), ")", style="font-family: 'times'; font-size: 12pt"),
                   p("2. Enter your ", code("Down Payment"), " amount (", span(em("in MYR"), style="color:blue"), ")", style="font-family: 'times'; font-size: 12pt"),
                   p("3. Slide to your ", code("Interest Rate"), "(", span(em("Annual Interest Rate in Percentage"), style="color:blue"), ")", style="font-family: 'times'; font-size: 12pt"),
                   p("4. Slide to your ", code("Loan Period"), "(", span(em("in Years"), style="color:blue"), ")", style="font-family: 'times'; font-size: 12pt"),
                   
                   h2("Bank rates:"),
                   p("Maybank : ", code("4.55%"), style="font-family: 'times'; font-size: 12pt"),
                   p("Public Bank : ", code("4.45%"), style="font-family: 'times'; font-size: 12pt"),
                   p("Standard Chartered Bank : ", code("4.67%"), style="font-family: 'times'; font-size: 12pt"),
                   p("Affin Bank : ", code("4.75%"), style="font-family: 'times'; font-size: 12pt"),
                   p("AmBank : ", code("4.45%"), style="font-family: 'times'; font-size: 12pt"),
                   p("Hong Leong Bank : ", code("4.80%"), style="font-family: 'times'; font-size: 12pt"),
                   p("Alliance Bank : ", code("4.65%"), style="font-family: 'times'; font-size: 12pt"),
                   p("CIMB Bank : ", code("4.65%"), style="font-family: 'times'; font-size: 12pt"),
                   p("RHB Bank : ", code("4.65%"), style="font-family: 'times'; font-size: 12pt"),
                   p("OCBC Bank : ", code("5.05%"), style="font-family: 'times'; font-size: 12pt"),
                   p("UOB : ", code("4.75%"), style="font-family: 'times'; font-size: 12pt"),
                   p("HSBC Bank : ", code("4.85%"), style="font-family: 'times'; font-size: 12pt")
                   
          ),
          tabPanel("Payment Summary", h3("Your monthly payment:",textOutput("resultPayment")), plotOutput("resultPie")),
          tabPanel("Payments Table", dataTableOutput("resultTable")))
      )
      
    ) #sidebarLayout ends
  ), #fluidPage ends
  
  server = function(input,output){
  #Monthly Payment Figure Output
  output$resultPayment <- renderText({
    
    initialLoan <- as.numeric(input$homeprice) - as.numeric(input$downpayment)
    balance <- initialLoan
    interestRate <- (input$irate/1200) #monthly rate
    year <- input$loanyear
    payment <- round(((balance*interestRate)/(1-(1+interestRate)^(-12*year))),2)
  }) #Monthly Payment Figure Output ends
  
  
  #Pie Chart Output
  output$resultPie <- renderPlot({
    
    initialLoan <- as.numeric(input$homeprice) - as.numeric(input$downpayment)
    interestRate <- (input$irate/1200) #monthly rate
    year <- input$loanyear
    
    firstrow <- c(0,"","","",initialLoan)
    balance <- initialLoan
    #rounded monthly payment
    payment <- round(((balance*interestRate)/(1-(1+interestRate)^(-12*year))),2)
    
    for(i in 1:((input$loanyear)*12)) {
      
      month <- as.numeric(i) #month
      interest <- round((interestRate * balance), 2) #monthly interest payment
      
      if (i != ((input$loanyear)*12)) {
        principal <- round((payment - interest), 2)
        balance <- round((balance - principal), 2)
        #interest <- (interestRate * balance) #monthly interest payment
        #principal <- (payment-interest)
        #balance <- (balance - principal)
        binded <- cbind(month, payment, interest, principal, balance)
      }      
      else {
        lastpayment <- balance + interest
        principal <- round((lastpayment - interest), 2)
        balance <- round((balance - principal), 2)
        binded <- cbind(month, lastpayment, interest, principal, balance)
      }
      
      if(exists("pie_table")!=TRUE) {
        pie_table <- cbind(month, payment, interest, principal, balance)
      }
      else {
        pie_table <- rbind(pie_table, binded) 
      }
    }
    
    total_interest <- sum(pie_table[,3]) #calculate the sum of interest paid
    total_principal <- sum(pie_table[,4]) #calculate the sum of principal paid
    pie_slice <- c(total_interest, total_principal)
    percentage_label <- c(round(pie_slice/sum(pie_slice)*100),0) #calculate the % of each slice
    pie_label <- c("Interest", "Principal") #naming the slice
    pie_label <- paste(pie_label, percentage_label) #adding the percentage value to the name of the slice
    pie_label <- paste(pie_label, "%", sep="") #adding the percentage, %, sign to the slice (without space)
    pie(pie_slice, pie_label, col=c("red", "cornsilk"), main="Payments Breakdown")
  }) #Pie Chart Output ends
  
  
  #Data Table Output
  output$resultTable <- renderDataTable({
    
    initialLoan <- as.numeric(input$homeprice) - as.numeric(input$downpayment)
    interestRate <- (input$irate/1200) #monthly rate
    year <- input$loanyear
    
    firstrow <- c(0,"","","",initialLoan)
    balance <- initialLoan
    #rounded monthly payment
    payment <- round(((balance*interestRate)/(1-(1+interestRate)^(-12*year))),2)
    
    for(i in 1:((input$loanyear)*12)) {
      
      month <- as.numeric(i) #month
      interest <- round((interestRate * balance), 2) #monthly interest payment
      
      if (i != ((input$loanyear)*12)) {
        principal <- round((payment - interest), 2)
        balance <- round((balance - principal), 2)
        #interest <- (interestRate * balance) #monthly interest payment
        #principal <- (payment-interest)
        #balance <- (balance - principal)
        binded <- cbind(month, payment, interest, principal, balance)
      }      
      else {
        lastpayment <- balance + interest
        principal <- round((lastpayment - interest), 2)
        balance <- round((balance - principal), 2)
        binded <- cbind(month, lastpayment, interest, principal, balance)
      }
      
      if(exists("complete_table")!=TRUE) {
        complete_table <- cbind(month, payment, interest, principal, balance)
      }
      else {
        complete_table <- rbind(complete_table, binded) 
      }
    }
    
    total_payments <- sum(complete_table[,2])
    total_interest <- sum(complete_table[,3])
    total_principal <- sum(complete_table[,4])
    
    tab <- cbind(total_principal,total_interest,total_payments)
    
    complete_table <- rbind(firstrow, complete_table)
    
    complete_table
    
  }) #Data Table Output ends
},
  
  options=list(width="100%", height=2000)

) #shinyApp ends
```
